export type ReferencePair = readonly [productCode: string, header: string]

export const ECO_REFERENCE_PAIRS: readonly ReferencePair[] = [
  ['', 'STT/No'],
  ['', 'Ngày/Date'],
  ['', 'A/C'],
  ['', 'Amenity'],
  ['', 'Type'],
  ['', 'FLT NO'],
  ['', 'DEP'],
  ['', 'ARR'],
  ['', 'STD/STA'],
  ['HM9', 'Mì Ý'],
  ['HM5', 'Miến xào'],
  ['HM8', 'Bánh chưng'],
  ['HM6', 'Bún xào'],
  ['HM7', 'Cơm chiên Thái'],
  ['HM2', 'Xôi mặn'],
  ['HM1', 'Xôi khúc'],
  ['HM4', 'Cơm bò'],
  ['HM3', 'Cơm dừa Malaysia'],
  ['40000294', 'Bánh mì'],
  ['HM14', 'Khoai viên chay Ấn + Paratha'],
  ['HM12', 'Cơm cà ri gà'],
  ['HM15', 'Cơm cà ri cá'],
  ['HM11', 'Cơm chiên Dương Châu chay'],
  ['HM13', 'Cơm Basmati cà ri chay'],
  ['', 'Thịt bò + rau tươi'],
  ['', 'Rau ăn mỳ/phở Úc'],
  ['', 'Rau ăn bánh mì Úc'],
  ['', 'Thịt bò + rau SGN–ADL'],
  ['', 'Set bánh mì tách thành phần SGN–ADL'],
  ['', 'Trứng luộc'],
  ['', 'Trứng SkyBoss'],
  ['', 'Tổng Trứng'],
  ['', 'Yogurt Sky Úc'],
  ['', 'Tổng cộng hotmeal đặt'],
  ['DC07', 'Tương cà'],
  ['DC06', 'Tương ớt'],
  ['DC08', 'Xì dầu'],
  ['DC10', 'Muối tiêu đường Ấn'],
  ['', 'Bộ thìa, dĩa, tăm theo hotmeal'],
  ['', 'Bộ thìa, dĩa, tăm dự phòng'],
  ['', 'Tổng bộ thìa, dĩa, tăm'],
  ['', 'Skyboss'],
  ['', 'Prebook'],
  ['', 'Macca nho khô Skyboss'],
  ['', 'Macca muối KAZ'],
  ['', 'Snack khoai tây/trái cây sấy'],
  ['', 'Rượu vang'],
  ['', 'Chăn C Skyboss'],
  ['', 'Bánh mì tròn + bơ lạc'],
  ['', 'Chăn 3in1 Prebook'],
  ['', 'Suối 350ml Skyboss + Prebook'],
  ['', 'Hạt điều Prebook'],
  ['', 'Macca thường'],
  ['', 'Xoài muối ớt GDS/DELUXE'],
  ['', 'Bia + khô gà + snack chả giò'],
  ['', 'Soda dâu + Macca'],
  ['', 'Suối tổ bay 1.5L'],
  ['DC02', 'Thùng xốp nhỏ'],
  ['DC01', 'Thùng xốp lớn'],
  ['DC09', 'Đá ướt kg'],
  ['DC03', 'Đá khô kg'],
  ['', 'Duty Free'],
  ['HL', 'Xe highlift'],
  ['TO', 'Xe tải nhỏ'],
  ['TOL', 'Top-up giờ chót'],
  ['', 'Ghi chú'],
]

export const SBB_REFERENCE_PAIRS = {
  'VIET-HAN-NHAT': [
    ['', 'Ngày'],
    ['', 'Số hiệu CB'],
    ['', 'STD'],
    ['', 'Số khách SBB'],
    ['SBB7', 'Phở bò'],
    ['SBB5', 'Miến gà'],
    ['SBB11', 'Xôi mặn'],
    ['SBB12', 'Bánh mì'],
    ['SBB1', 'Díp cuốn'],
    ['SBB21', 'Trứng cuốn quốc tế'],
    ['SBB20', 'Trái cây'],
    ['SBB10', 'Rau câu dừa'],
    ['SBB9', 'Bánh mì tròn & bơ truyền thống'],
    ['', 'Bánh sừng bò thanh long'],
    ['SBB18', 'Ngũ cốc'],
    ['SBB22', 'Bánh sừng bò quốc tế'],
    ['SBB29', 'Yogurt quốc tế'],
    ['SBB2', 'Nước ép cà rốt'],
    ['SBB3', 'Dưa hấu'],
    ['SBB4', 'Nước mía'],
    ['SBB14', 'Cafe đen 480ml'],
    ['', 'Lá chuối 18×18, túi 5 lá'],
    ['SBB-VHN-PEPPER', 'Muối tiêu'],
    ['SBB34', 'Trang trí cocktail'],
    ['', 'Cocktail'],
    ['', 'Macca nho khô'],
    ['', 'Chăn SBB BH≥4h'],
    ['', 'Gối tựa đầu SBB BH≥4h'],
    ['', 'Ghi chú'],
  ],
  'CHAY(VIỆT-HÀN-NHẬT)': [
    ['', 'Ngày'],
    ['', 'Số hiệu CB'],
    ['', 'STD'],
    ['', 'Tổng khách chay'],
    ['SBB25', 'Bún xào chay thường'],
    ['SBB40', 'Cơm chiên Dương Châu chay'],
    ['SBB42', 'Cơm cà ri Ấn chay'],
    ['SBB43', 'Khoai viên + Paratha'],
    ['SBB44', 'Díp cuốn chay'],
    ['SBB45', 'Salad chay'],
    ['SBB46', 'Salad đậu kiểu Ấn'],
    ['SBB29', 'Yogurt'],
    ['SBB20', 'Set hoa quả 3 miếng'],
  ],
  'ẤN': [
    ['', 'Ngày'],
    ['', 'Số hiệu CB'],
    ['', 'STD'],
    ['', 'Số khách SBB'],
    ['SBB41', 'Cơm cà ri gà'],
    ['SBB42', 'Cơm cà ri Ấn chay'],
    ['SBB-IN-BUN-XAO', 'Bún xào Singapore SBB'],
    ['SBB44', 'Diếp cuốn chay'],
    ['SBB20', 'Set hoa quả'],
    ['SBB9', 'Bánh mì & bơ'],
    ['', 'Bánh sừng bò thanh long'],
    ['SBB18', 'Ngũ cốc'],
    ['SBB22', 'Bánh sừng bò quốc tế'],
    ['SBB29', 'Yogurt'],
    ['SBB2', 'Nước ép cà rốt'],
    ['SBB3', 'Dưa hấu'],
    ['SBB4', 'Nước mía'],
    ['SBB14', 'Cafe đen'],
    ['SBB47', 'Lá chuối 18×18'],
    ['SBB34', 'Trang trí cocktail'],
    ['', 'Cocktail'],
    ['', 'Macca nho'],
    ['', 'Chăn SBB'],
    ['', 'Gối tựa đầu SBB'],
    ['', 'Ghi chú'],
  ],
  'ÚC&KAZ': [
    ['', 'Ngày'],
    ['', 'Số hiệu CB'],
    ['', 'STD'],
    ['', 'Số khách SBB'],
    ['', 'Meal box thường'],
    ['', 'Meal box chay'],
    ['SBB5', 'Miến gà'],
    ['SBB12', 'Bánh mì'],
    ['SBB39', 'Bánh chưng'],
    ['SBB23', 'Cá Basa'],
    ['SBB7', 'Phở bò'],
    ['SBB37', 'Bún bò Huế'],
    ['SBB11', 'Xôi mặn'],
    ['SBB24', 'Gà Gravy'],
    ['', 'Sandwich phô mai'],
    ['', 'Burger'],
    ['SBB27', 'Salad rau củ tôm'],
    ['SBB1', 'Díp cuốn'],
    ['SBB9', 'Bánh mì tròn & bơ'],
    ['SBB22', 'Bánh sừng bò'],
    ['', 'Bánh sừng bò thanh long'],
    ['SBB10', 'Rau câu dừa'],
    ['SBB49', 'Bánh mousse dừa'],
    ['SBB28', 'Bánh mochi'],
    ['SBB29', 'Yogurt'],
    ['SBB30', 'Trái cây 600g/khay'],
    ['SBB20', 'Trái cây 90g'],
    ['SBB31', 'Quýt kg'],
    ['SBB36', 'Táo Rockit ống'],
    ['SBB32', 'Nho xanh Úc kg'],
    ['SBB2', 'Nước ép cà rốt'],
    ['SBB3', 'Dưa hấu'],
    ['SBB4', 'Nước mía'],
    ['SBB33', 'Finger food/khay'],
    ['SBB14', 'Cafe đen'],
    ['SBB47', 'Lá chuối 18×18'],
    ['SBB48', 'Lá chuối 9×9'],
    ['SBB-AUKAZ-PEPPER', 'Muối tiêu'],
    ['SBB34', 'Trang trí cocktail'],
    ['', 'Cocktail'],
    ['', 'Macca nho khô'],
    ['', 'Hạt điều'],
    ['', 'Hạt Macca đen'],
    ['', 'Bộ dụng cụ ăn SBB'],
    ['', 'Bộ kit SBB'],
    ['', 'Chăn SBB'],
    ['', 'Gối tựa đầu SBB'],
    ['', 'Tấm trải nệm ghế'],
    ['', 'Ghi chú'],
  ],
} as const satisfies Record<string, readonly ReferencePair[]>

export const SBB_REFERENCE_LAST_COLUMNS = {
  'VIET-HAN-NHAT': 'AC',
  'CHAY(VIỆT-HÀN-NHẬT)': 'M',
  'ẤN': 'Y',
  'ÚC&KAZ': 'AW',
} as const
